[project]
name = "home-library"
version = "0.1.0"
description = ""
authors = [
    {name = "blackfyre",email = "seanrp504@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-extra-types (>=2.10.5,<3.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)"
]

[tool.poetry]
packages = [{include = "home_library", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
